import {
    NAV_ITEM_TYPE_ITEM,
    NAV_ITEM_TYPE_COLLAPSE,
} from '@/constants/navigation.constant'
import { ADMIN, COMPANY, COMPANY_USER } from '@/constants/roles.constant'

import type { NavigationTree } from '@/@types/navigation'

const navigationConfig: NavigationTree[] = [
    {
        key: 'dashboard',
        path: '/dashboard',
        title: 'Dashboard',
        translateKey: 'nav.home',
        icon: 'dashboardAnalytic',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [],
    },
    {
        key: 'users',
        path: '/users',
        title: 'Users',
        translateKey: 'nav.singleMenuItem',
        icon: 'users',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY],
        subMenu: [],
    },
    {
        key: 'companies',
        path: '/companies',
        title: 'Companies',
        translateKey: 'nav.singleMenuItem',
        icon: 'companies',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN],
        subMenu: [],
    },
    {
        key: 'businessTracker',
        path: '/business-tracker',
        title: 'Business Tracker',
        translateKey: 'nav.singleMenuItem',
        icon: 'projects',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [],
    },
    {
        key: 'transactions',
        path: '/transactions',
        title: 'Transactions',
        translateKey: 'nav.singleMenuItem',
        icon: 'transactions',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [],
    },
    {
        key: 'goals',
        path: '/goals',
        title: 'Goals',
        translateKey: 'nav.singleMenuItem',
        icon: 'goals',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [],
    },
    {
        key: 'schedule',
        path: '/schedule',
        title: 'Schedule',
        translateKey: 'nav.singleMenuItem',
        icon: 'calendar',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [],
    },
    {
        key: 'collapseMenu',
        path: '',
        title: 'Reports',
        translateKey: 'nav.collapseMenu.collapseMenu',
        icon: 'graph',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [COMPANY, COMPANY_USER],
        subMenu: [
            {
                key: 'collapseMenu.performance',
                path: '/reports/performance',
                title: 'Performance',
                translateKey: 'nav.collapseMenu.performance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [COMPANY, COMPANY_USER],
                subMenu: [],
            },
            {
                key: 'collapseMenu.monthly',
                path: '/reports/monthly',
                title: 'Monthly',
                translateKey: 'nav.collapseMenu.monthly',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [COMPANY, COMPANY_USER],
                subMenu: [],
            },
            {
                key: 'collapseMenu.monthlyPerformance',
                path: '/reports/monthly-performance',
                title: 'Monthly Performance',
                translateKey: 'nav.collapseMenu.monthlyPerformance',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [COMPANY, COMPANY_USER],
                subMenu: [],
            },
            {
                key: 'collapseMenu.usersMatrices',
                path: '/reports/users-matrices',
                title: 'Users Metrics',
                translateKey: 'nav.collapseMenu.usersMatrices',
                icon: '',
                type: NAV_ITEM_TYPE_ITEM,
                authority: [COMPANY],
                subMenu: [],
            },
        ],
    },
]

export default navigationConfig
